name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/dcslv/dcslv
            git pull origin main
            docker stop dcslv-app
            docker rm dcslv-app
            docker build -t dcslv-app .
            docker run -d \
              --name dcslv-app \
              --network web \
              --restart always \
              -p 3000:3000 \
              dcslv-app
